// <auto-generated />
using System;
using DaoMinhHieu0021867.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaoMinhHieu0021867.Migrations
{
    [DbContext(typeof(ApplicationDbContext0021867De11005))]
    [Migration("20250818091817_AddNgaySuaToRepair")]
    partial class AddNgaySuaToRepair
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Equipment0021867De11005", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaThietBi")
                        .IsUnique();

                    b.HasIndex("TenThietBi")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Repair0021867De11005", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanSua")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Technician0021867De11005", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKyThuatVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKyThuatVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("MaKyThuatVien")
                        .IsUnique();

                    b.HasIndex("TenKyThuatVien")
                        .IsUnique();

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Repair0021867De11005", b =>
                {
                    b.HasOne("DaoMinhHieu0021867.Entities.Equipment0021867De11005", "Equipment")
                        .WithMany("Repairs")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaoMinhHieu0021867.Entities.Technician0021867De11005", "Technician")
                        .WithMany("Repairs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Equipment0021867De11005", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("DaoMinhHieu0021867.Entities.Technician0021867De11005", b =>
                {
                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
